
import React from 'react';

export const CARRIERS = [
  { name: 'Rogers', gateway: 'pcs.rogers.com', prefixes: ['416', '647', '905', '289', '437'] },
  { name: 'Bell', gateway: 'txt.bell.ca', prefixes: ['514', '438', '450', '579', '819', '873'] },
  { name: 'Telus', gateway: 'msg.telus.com', prefixes: ['604', '778', '236', '250', '403', '587', '825', '780'] },
  { name: 'Fido', gateway: 'fido.ca', prefixes: [] },
  { name: 'Virgin Plus', gateway: 'vmobile.ca', prefixes: [] },
  { name: 'Koodo', gateway: 'msg.telus.com', prefixes: [] },
  { name: 'Freedom', gateway: 'txt.freedommobile.ca', prefixes: [] },
  { name: 'Videotron', gateway: 'vmobile.ca', prefixes: [] },
  { name: 'SaskTel', gateway: 'sms.sasktel.com', prefixes: ['306', '639'] },
];

export const TRANSLATIONS = {
  EN: {
    title: 'Support-Eye',
    subtitle: 'Instant Visual Assistance',
    login: 'Technician Login',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In',
    startSession: 'Start New Session',
    phoneNumber: 'Client Phone Number',
    phonePlaceholder: '+1 (514) 000-0000',
    sendSms: 'Send SMS Invite',
    waitingClient: 'Waiting for client to connect...',
    connected: 'Live Visual Connection',
    tools: 'Annotation Tools',
    pointer: 'Laser Pointer',
    rect: 'Rectangle',
    circle: 'Circle',
    arrow: 'Arrow',
    text: 'Text',
    clear: 'Clear All',
    endSession: 'End Session',
    clientWelcome: 'Welcome to Support-Eye',
    clientInstructions: 'Your technician is ready to assist. Please allow camera access.',
    allowCamera: 'Allow Camera',
    cameraError: 'Camera access denied or not available.',
    sessionEnded: 'The support session has ended. Thank you.',
    carrierDetection: 'Carrier detected',
    unknownCarrier: 'Unknown Carrier (Defaulting to Multi-Gateway)',
    language: 'Language',
  },
  FR: {
    title: 'Support-Eye',
    subtitle: 'Assistance Visuelle Instantanée',
    login: 'Connexion Technicien',
    username: 'Utilisateur',
    password: 'Mot de passe',
    signIn: 'Se Connecter',
    startSession: 'Démarrer une session',
    phoneNumber: 'Numéro de téléphone du client',
    phonePlaceholder: '+1 (514) 000-0000',
    sendSms: 'Envoyer Invitation SMS',
    waitingClient: 'En attente de connexion du client...',
    connected: 'Connexion Visuelle en Direct',
    tools: 'Outils d\'annotation',
    pointer: 'Pointeur Laser',
    rect: 'Rectangle',
    circle: 'Cercle',
    arrow: 'Flèche',
    text: 'Texte',
    clear: 'Effacer tout',
    endSession: 'Terminer la session',
    clientWelcome: 'Bienvenue sur Support-Eye',
    clientInstructions: 'Votre technicien est prêt. Veuillez autoriser l\'accès à la caméra.',
    allowCamera: 'Autoriser la caméra',
    cameraError: 'Accès caméra refusé ou non disponible.',
    sessionEnded: 'La session de support est terminée. Merci.',
    carrierDetection: 'Opérateur détecté',
    unknownCarrier: 'Opérateur inconnu (Utilisation multi-passerelle)',
    language: 'Langue',
  }
};
